### ISSUE TITLE
Formular-field "reCaptcha Response Here" in Version 1.1.9 stops form working

### ISSUE THREAD

**Issue by gcPhil** [IQComputing/wpcf7-recaptcha#1]
As soon I update your Plugin "Contact Form 7 - reCaptcha v2" from 1.1.8 to Version 1.1.9 I get an extra text-field with the Text "_reCaptcha Response Here_" next to the Recaptcha-box. This lets sending the form fail, even when the reCaptcha-task is solved correct.

**Comment by IQComputing** [comment]
Are there any JavaScript errors in your JS console? Could you post a link to your website?

**Comment by gcPhil** [comment]
Thank you for your reply. In the meantime I have already received help in the forum at https://wordpress.org/support/topic/recaptcha-response-here-error-in-1-1-9/ that's why I close this issue here now.
